/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Food' : IDL.Null,
  'Health' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Shopping' : IDL.Null,
  'Housing' : IDL.Null,
  'Other' : IDL.Null,
  'Transport' : IDL.Null,
  'Education' : IDL.Null,
  'Utilities' : IDL.Null,
});
export const CategorySummary = IDL.Record({
  'overspent' : IDL.Bool,
  'budgetLimit' : IDL.Float64,
  'spentThisMonth' : IDL.Float64,
  'percentageUsed' : IDL.Float64,
  'category' : Category,
});
export const MonthlyTrend = IDL.Record({
  'month' : IDL.Text,
  'total' : IDL.Float64,
});
export const SpendingAnalysis = IDL.Record({
  'categorySummaries' : IDL.Vec(CategorySummary),
  'savingsPotential' : IDL.Float64,
  'monthlyTrends' : IDL.Vec(MonthlyTrend),
  'topSpendingCategories' : IDL.Vec(CategorySummary),
  'healthScore' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Budget = IDL.Record({
  'limit' : IDL.Float64,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, Category, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'analyzeSpending' : IDL.Func([], [SpendingAnalysis], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getMonthlyTotals' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Tuple(Category, IDL.Float64))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBudget' : IDL.Func([Category, IDL.Float64], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, Category, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Food' : IDL.Null,
    'Health' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Shopping' : IDL.Null,
    'Housing' : IDL.Null,
    'Other' : IDL.Null,
    'Transport' : IDL.Null,
    'Education' : IDL.Null,
    'Utilities' : IDL.Null,
  });
  const CategorySummary = IDL.Record({
    'overspent' : IDL.Bool,
    'budgetLimit' : IDL.Float64,
    'spentThisMonth' : IDL.Float64,
    'percentageUsed' : IDL.Float64,
    'category' : Category,
  });
  const MonthlyTrend = IDL.Record({
    'month' : IDL.Text,
    'total' : IDL.Float64,
  });
  const SpendingAnalysis = IDL.Record({
    'categorySummaries' : IDL.Vec(CategorySummary),
    'savingsPotential' : IDL.Float64,
    'monthlyTrends' : IDL.Vec(MonthlyTrend),
    'topSpendingCategories' : IDL.Vec(CategorySummary),
    'healthScore' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Budget = IDL.Record({ 'limit' : IDL.Float64, 'category' : Category });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, Category, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'analyzeSpending' : IDL.Func([], [SpendingAnalysis], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getMonthlyTotals' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Tuple(Category, IDL.Float64))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBudget' : IDL.Func([Category, IDL.Float64], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, Category, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };