/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Budget { 'limit' : number, 'category' : Category }
export type Category = { 'Food' : null } |
  { 'Health' : null } |
  { 'Entertainment' : null } |
  { 'Shopping' : null } |
  { 'Housing' : null } |
  { 'Other' : null } |
  { 'Transport' : null } |
  { 'Education' : null } |
  { 'Utilities' : null };
export interface CategorySummary {
  'overspent' : boolean,
  'budgetLimit' : number,
  'spentThisMonth' : number,
  'percentageUsed' : number,
  'category' : Category,
}
export interface Expense {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : Category,
  'amount' : number,
}
export interface MonthlyTrend { 'month' : string, 'total' : number }
export interface SpendingAnalysis {
  'categorySummaries' : Array<CategorySummary>,
  'savingsPotential' : number,
  'monthlyTrends' : Array<MonthlyTrend>,
  'topSpendingCategories' : Array<CategorySummary>,
  'healthScore' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[number, Category, string, string], bigint>,
  'analyzeSpending' : ActorMethod<[], SpendingAnalysis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getBudgets' : ActorMethod<[], Array<Budget>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMonthlyTotals' : ActorMethod<[bigint, bigint], Array<[Category, number]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBudget' : ActorMethod<[Category, number], undefined>,
  'updateExpense' : ActorMethod<
    [bigint, number, Category, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];